### ISSUE TITLE
Возврат на предыдущую страницу.

### ISSUE THREAD

**Issue by leaango** [fedorovmichael/tickets#14]
Steps:
1. Зайди на главную страницу сайта
2. Выбери ивент
3. Нажми на кнопку возврата <-
Expected result:
Возврат на главную страницу сайта
Actual result:
Возврат на предыдущий сайт

P.S. Обрати внимание, что если до нажатия на ивент был фильтр, то после возвращения из ивента этот фильтр должен быть сохранен.

**Comment by leaango** [comment]
Решено добавить дополнительную кнопку возврата в главное меню кроме Х.

**Comment by fedorovmichael** [comment]
was made restyling for edit show page

**Comment by leaango** [comment]
Closed
