### ISSUE TITLE
Выбор в категориях с подкатегориями

### ISSUE THREAD

**Issue by leaango** [fedorovmichael/tickets#18]
Выбор в категориях "Концерт" и "Театр" (т.е. в категориях с подкатегориями) непонятен. К примеру, при выборе подкатегории "Эстрада" в категории "Концерт" галочка с "Концерта" должна автоматически убираться.

![image](https://user-images.githubusercontent.com/29542666/27330544-878e59f8-55c2-11e7-8663-8fbe4c43e8a5.png)

**Comment by fedorovmichael** [comment]
при выборе subtype галочка на type отменяется

**Comment by leaango** [comment]
Closed.
