### ISSUE TITLE
"Рука" на событии в фокусе

### ISSUE THREAD

**Issue by leaango** [fedorovmichael/tickets#2]
Steps:
1. Открой главную страницу сайта
2. Подведи мышку к какому-либо событию (к примеру концерт Nautilus Pompilius)

Expected result:
"Рука" на событии находящемся в фокусе

Actual result:
Нет "руки". Не понятно можно ли выбрать это событие или нет.

**Comment by fedorovmichael** [comment]
fixed

**Comment by leaango** [comment]
Closed.
