### ISSUE TITLE
С открытием каждого нового ивента добавляются сеансы с прошлых открытых ивентов.

### ISSUE THREAD

**Issue by leaango** [fedorovmichael/tickets#22]
Теперь с открытием каждого нового ивента добавляются сеансы с прошлых открытых ивентов.
К примеру на Наргиз должно быть 3 сеанса, а их уже 10.

![image](https://user-images.githubusercontent.com/29542666/27429326-6bfc47f4-574d-11e7-9e81-de9449845eef.png)

**Comment by fedorovmichael** [comment]
fixed, need to check
