### ISSUE TITLE
Выбор в категории дата

### ISSUE THREAD

**Issue by leaango** [fedorovmichael/tickets#27]
Выбор в категории дата должен быть мульти . Например можно выбрать и сегодня и завтра. Если выбираешь одну из опций в дате, то с и по должно быть disabled.

![image](https://user-images.githubusercontent.com/29542666/27511808-3c744500-5936-11e7-9f62-2d2ce405a671.png)

**Comment by fedorovmichael** [comment]
fixed, need to check
