### ISSUE TITLE
Иконки для категории и даты в верхнем меню

### ISSUE THREAD

**Issue by leaango** [fedorovmichael/tickets#29]
Иконки для категории и даты в верхнем меню надо поменять, чтобы было понятно, что это сортировка.  Что-то со стрелками вверх-вниз. Можно использовать те же как и в цене и названии.

![image](https://user-images.githubusercontent.com/29542666/27511834-b609e3ca-5936-11e7-992b-c90f8422d49e.png)

**Comment by fedorovmichael** [comment]
fixed, sorting not works  for date, types
