### ISSUE TITLE
Дата начала мероприятия

### ISSUE THREAD

**Issue by leaango** [fedorovmichael/tickets#3]
Если дата начала и окончания мероприятия совпадают, то должна появляться только одна дата. 
Не нужно печатать одну и ту же дату 2 раза.

![image](https://user-images.githubusercontent.com/29542666/27327625-ce8da102-55b7-11e7-9997-2d590c38c99b.png)

**Comment by fedorovmichael** [comment]
fixed

**Comment by leaango** [comment]
Closed.
