### ISSUE TITLE
Поиск по дате для многодневных мероприятий

### ISSUE THREAD

**Issue by leaango** [fedorovmichael/tickets#39]
Дата спектакля Мизери определена как 01.07-08.07. Это значит, что при поиске по любой из дат из этого промежутка событие должно быть найдено (т.е. например только 01.07 или 01.07-02.07 или 06.07-08.07 и т.д.) На самом деле мероприятие находится только если выбрать в фильтре 01.07-08.07.

**Comment by fedorovmichael** [comment]
fixed
