### ISSUE TITLE
Минимальная цена на билеты

### ISSUE THREAD

**Issue by leaango** [fedorovmichael/tickets#4]
Если минимальная и максимальная цена мероприятия совпадают, то должна появляться только одна цена. 
Не нужно печатать одну и ту же цену 2 раза.

![image](https://user-images.githubusercontent.com/29542666/27327776-59118afa-55b8-11e7-929b-2a125cee9981.png)

**Comment by fedorovmichael** [comment]
fixed

**Comment by leaango** [comment]
Closed.
