### ISSUE TITLE
Поиск по дате в неправильном формате (от Вадима) 

### ISSUE THREAD

**Issue by leaango** [fedorovmichael/tickets#41]
Поиск: Дает возможность вводить дату в левом формате. При этом что-то ищет и выдаёт странные результаты поиска. Вот так например 
![image](https://user-images.githubusercontent.com/29542666/27808087-2982ec84-604e-11e7-9dfd-8ff916bc143f.png)

**Comment by fedorovmichael** [comment]
fixed, added validation for dates
